version: '3.3'

services:
  db:
    image: mysql:5.7.22
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - 3306
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: contact_api
volumes:
  db_data: {}